[package]
name = "sys-stat"
version = "0.2.0"
authors = ["lilydjwg <lilydjwg@gmail.com>"]
edition = "2021"

[dependencies]
eyre = "*"
uname = "*"
graphite-client = { version = "*", path = "../graphite-client" }
num_cpus = "*"

[profile.release]
lto = true
